services:
  - type: web
    name: tu-nombre-de-servicio
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /.*/
        destination: /index.html
